### ISSUE TITLE
Feature request: scanradius modifier

### ISSUE THREAD

**Issue by SlimeDog** [FrankHeijden/Insights#2]
Spigot 1.14.2
Insights 2.3.0

**scanradius 25** times out. Please implement a modifier to scan only above the surface.

**Comment by FrankHeijden** [comment]
I don't know about this one, this cancels out a lot of things. It also does not work that perfectly in terms of scanning as it does not guarantee it will scan all things. 

In terms of timing out, this happens because the plugin is loading a huge amount of chunks when scanning in a radius of 25 chunks ((25+25+1)*(25+25+1) = 2601 chunks) 

I am implementing a system for loading chunks asynchronously, using Paper's functionality.

**Comment by SlimeDog** [comment]
Oh, radius is chunks. I don't need that large a scan -- I'm just looking for entities in my immediate surroundings. I'll try **scanradius 3**.

**Comment by SlimeDog** [comment]
It would be nice to be able to configure a **scanradius** default. Then
> **scanradius**

without parameters would be equivalent to
> **scanradius defaultRadius currentWorld all**

**Comment by FrankHeijden** [comment]
Although I do not like the idea of having a default value for the /scanradius command, I think I can implement this by tabcomplete. This way the default value can be tab completed when typing the command.

Another quick fix is to define an alias in commands.yml;
```
scanradiusdefault:
  - scanradius 3 $1-
```

**Comment by SlimeDog** [comment]
TabCompletion will do nicely. I already created the commands.yml alias. :)
