### ISSUE TITLE
Incompatibility - WildStacker

### ISSUE THREAD

**Issue by Acenox** [FrankHeijden/Insights#8]
Hello,

I am writing this report to let you know that there is a compatibility problem with WildStacker. When I install Insights, Wildstacker spammed me with error in my console. but as soon as I uninstall Insights, I have no more problems.

Spigot: Stellarspigot (Fork TacoSpigot-1.8.8)
Insights version: 2.9.1

Error: https://pastebin.com/3hcW3Zdz

Best regards,

**Comment by FrankHeijden** [comment]
Hey, thank you for reporting this!

I think it has to do because the plugin updated to v3.0.0, which puts me a bit in a difficult position for this issue, as I do not have purchased this premium plugin. In the recent update, I added a few fixes for compatibility with other plugins; so I have a compiled version here without any hooks into WildStacker, which might already solve the issue with WildStacker without directly hooking into the plugin itself. Could you maybe please test this version out; place some hoppers/spawners around and see if you have any issues with WildStacker and Insights?

I will also make an issue report on the github of the WildStackerAPI to update the repo to their v3.0.0 version.

Best regards,
Frank
[Insights.jar.zip](https://github.com/FrankHeijden/Insights/files/4144815/Insights.jar.zip)

**Comment by FrankHeijden** [comment]
Linked issue report: https://github.com/OmerBenGera/WildStackerAPI/issues/1

**Comment by Acenox** [comment]
Hello,

The error is still present.

Best regards,

**Comment by FrankHeijden** [comment]
Thank you for responding so quickly, I think it is out of my reach for now then to fix the issue immediately, I will have to wait on an update on this on WildStacker's end.

**Comment by FrankHeijden** [comment]
Hey, I think I may have found something; could you please test this version?
[Insights.jar.zip](https://github.com/FrankHeijden/Insights/files/4145409/Insights.jar.zip)

**Comment by Acenox** [comment]
Hello, The problem is solved! Thank you :)
